[package]
edition = "2021"
name = "time_sessions"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.0"
clap = {version = "3.1.18", features = ["derive"]}
open = "2.1.3"
